version: '3'

services:
  redis:
    image: redis:4.0.11-alpine

  dewey:
    image: dewey:v1
    ports:
      - "8080:8080"
    environment:
      DEWEY_SECRET_KEY: "someReallyl0g5tr1ng"
      DEWEY_POSTGRES_HOST: "172.28.128.3"
      DEWEY_POSTGRES_PASSWORD: "Aiy5vah0cheep"
      STATIC_ROOT: "/tmp/django"
    depends_on:
      - redis

  dewey-celery-worker:
    image: dewey:v1
    entrypoint: /code/bin/dewey-celery.sh
    command: worker
    environment:
      DEWEY_POSTGRES_HOST: "172.28.128.3"
      DEWEY_POSTGRES_PASSWORD: "Aiy5vah0cheep"
    depends_on:
      - dewey
      - redis

  dewey-celery-scheduler:
    image: dewey:v1
    entrypoint: /code/bin/dewey-celery.sh
    command: beat
    environment:
      DEWEY_POSTGRES_HOST: "172.28.128.3"
      DEWEY_POSTGRES_PASSWORD: "Aiy5vah0cheep"
    depends_on:
      - dewey
      - redis

  dewey-celery-flower:
    image: dewey:v1
    entrypoint: /code/bin/dewey-celery.sh
    command: flower
    environment:
      DEWEY_POSTGRES_HOST: "172.28.128.3"
      DEWEY_POSTGRES_PASSWORD: "Aiy5vah0cheep"
    ports:
      - "5555:5555"
    depends_on:
      - dewey
      - redis
